env:
  coefficient_dict:
    p_b: 1.0
    p_d: 1.0
    r_c: 0.0
  cropped_map_size: 64
  n_maps: 400
  n_steps_per_map: 20
  no_masking: true
  original_map_path: ./resource/usc.png
  original_map_scale: 3.4375
  preset_map_path: ./resource/setup_400.json
  ratio_coverage: 0.0125
eval:
  evaluation_config:
    env_config:
      evaluation: true
      n_maps: 3
      preset_map_path: null
    exploration:
      explore: false
  evaluation_duration: 3
  evaluation_interval: 5
  evaluation_num_workers: 3
explore:
  exploration_config:
    type: StochasticSampling
  explore: true
report:
  min_sample_timesteps_per_iteration: 1000
resource:
  num_cpus_per_worker: 2
  num_gpus: 0
  num_gpus_per_worker: 0
rollout:
  num_envs_per_worker: 1
  num_rollout_workers: 4
stop:
  training_iteration: 500
train:
  optimization_config:
    actor_learning_rate: 0.0001
    critic_learning_rate: 0.001
    entropy_learning_rate: 0.0001
  num_steps_sampled_before_learning_starts: 50000
  replay_buffer_config:
    capacity: 50000
  target_network_update_freq: 0
  tau: 0.005
  gamma: 0.1
  grad_clip: 40.0
  train_batch_size: 32
