env:
  n_bs: 2
  map_size: 256
  action_space_size: 32
  n_maps: 500
  n_episodes_per_map: 2
  n_steps_truncate: 500
  dataset_dir: resource/usc_old_sparse
  no_masking: false
eval:
  evaluation_config:
    env_config:
      evaluation: true
      n_maps: 100
      n_episodes_per_map: 1
    exploration:
      explore: false
  evaluation_duration: 1
  evaluation_interval: 5
  evaluation_num_workers: 0
explore:
  exploration_config:
    type: StochasticSampling
  explore: true
report:
  min_sample_timesteps_per_iteration: 1000  # keep it the same as n_steps_truncate * num_rollout_workers
resource:
  num_cpus_per_worker: 1
  num_gpus: 0
  num_gpus_per_worker: 0
rollout:
  num_envs_per_worker: 1
  num_rollout_workers: 2
  batch_mode: truncate_episodes
  rollout_fragment_length: 500  # n_steps_truncate
stop:
  training_iteration: 1000  # n_episodes_per_map x n_maps
train:
  lr: 1.0e-05
  gamma: 0.9
  grad_clip: 40.0
  train_batch_size: 2000
  sgd_minibatch_size: 128
  num_sgd_iter: 20
  model:
    fcnet_hiddens: [128, 128]
    fcnet_activation: relu
agent:
  data_saving_interval: 50