env:
  coefficient_dict:
    p_b: 1.0
    p_d: 1.0
    r_c: 0.1
  cropped_map_size: 64
  n_maps: 100
  n_steps_per_map: 10
  no_masking: true
  original_map_path: ./resource/usc.png
  original_map_scale: 3.4375
  preset_map_path: ./resource/setup.json
  ratio_coverage: 0.0125
eval:
  evaluation_config:
    env_config:
      evaluation: true
      n_maps: 3
      preset_map_path: null
    explore: false
  evaluation_duration: 3
  evaluation_interval: 5
explore:
  exploration_config:
    epsilon_timesteps: 10
    final_epsilon: 0.02
    initial_epsilon: 1.0
    type: EpsilonGreedy
  explore: true
report:
  min_sample_timesteps_per_iteration: 10
resource:
  num_cpus_per_worker: 2
  num_gpus: 0
  num_gpus_per_worker: 0
rollout:
  num_envs_per_worker: 1
  num_rollout_workers: 4
stop:
  training_iteration: 10
train:
  lr: 5.0e-05
  train_batch_size: 32
  sgd_minibatch_size: 16
  num_sgd_iter: 10