env:
  coefficient_dict:
    p_d: 1.0
    r_c: 1.0
  map_size: 256
  action_space_size: 64
  n_maps: 100
  n_steps_per_map: 16
  dataset_dir: resource/usc_old
  no_masking: True
  evaluation: true
eval:
  evaluation_config:
    env_config:
      evaluation: true
      n_maps: 50
    exploration:
      explore: false
  evaluation_duration: 1
  evaluation_interval: 1
  evaluation_num_workers: 2
explore:
  exploration_config:
    type: StochasticSampling
  explore: true
report:
  min_sample_timesteps_per_iteration: 512  # keep it the same as n_steps_per_map
resource:
  num_cpus_per_worker: 1
  num_gpus: 0
  num_gpus_per_worker: 0
rollout:
  num_envs_per_worker: 1
  num_rollout_workers: 4
stop:
  training_iteration: 500
train:
  lr: 1.0e-05
  gamma: 0.9
  grad_clip: 0.5
  train_batch_size: 512
  sgd_minibatch_size: 64
  num_sgd_iter: 30
  model:
#    fcnet_hiddens: [ 128, 128 ]
    fcnet_activation: relu