env:
  coefficient_dict:
    p_b: 1.0
    p_d: 1.0
    r_c: 1.0
  cropped_map_size: 64
  action_space_size: 32
  n_maps: 400
  n_steps_per_map: 20
  no_masking: false
  original_map_path: ./resource/usc.png
  original_map_scale: 3.4375
  preset_map_path: ./resource/setup_400.json
  ratio_coverage: 0.0125
eval:
  evaluation_config:
    env_config:
      evaluation: true
      n_maps: 1
      preset_map_path: null
    exploration:
      explore: false
  evaluation_duration: 3
  evaluation_interval: 5
  evaluation_num_workers: 3
explore:
  exploration_config:
    type: StochasticSampling
  explore: true
report:
  min_sample_timesteps_per_iteration: 1000
resource:
  num_cpus_per_worker: 2
  num_gpus: 0
  num_gpus_per_worker: 0
rollout:
  num_envs_per_worker: 1
  num_rollout_workers: 4
stop:
  training_iteration: 500
train:
  lr: 1.0e-05
  gamma: 0.0
  grad_clip: 40.0
  train_batch_size: 32
  sgd_minibatch_size: 8
  num_sgd_iter: 30
