env:
  coefficient_dict:
    p_b: 1.0
    p_d: 1.0
    r_c: 0.1
  cropped_map_size: 64
  n_maps: 100
  n_steps_per_map: 50
  no_masking: true
  original_map_path: ./resource/usc.png
  original_map_scale: 3.4375
  preset_map_path: ./resource/setup.json
  ratio_coverage: 0.0125
eval:
  evaluation_config:
    env_config:
      evaluation: true
      n_maps: 3
      preset_map_path: null
    explore: false
  evaluation_duration: 3
  evaluation_interval: 5
explore:
  exploration_config:
    epsilon_timesteps: 100000
    final_epsilon: 0.02
    initial_epsilon: 1.0
    type: EpsilonGreedy
  explore: true
report:
  min_sample_timesteps_per_iteration: 1000
resource:
  num_cpus_per_worker: 2
  num_gpus: 0
  num_gpus_per_worker: 0
rollout:
  num_envs_per_worker: 1
  num_rollout_workers: 4
stop:
  training_iteration: 1000
train:
  num_steps_sampled_before_learning_starts: 50000
  replay_buffer_config:
    capacity: 50000
  target_network_update_freq: 5
  train_batch_size: 32
